### PR TITLE
Fix "forever spinning" (#211)

### LINKED ISSUE #211: Test keeps spinning after test run
When I run NUnit based tests the test status keeps spinning after the test run. Is that a known issue? It was working before, but I didn't use vscode for quite a while (about 4 months)
image

### PR DESCRIPTION
**Pull request by GeorchW**
There used to be an useless and complicated procedure based on file watching to detect new results files, which was error-prone and led to race conditions. 

`dotnet test` writes the results files right before exiting, so we don't need any file watching; we can just wait for the process to terminate and then read the results. This simplifies the code a bit and removes the dependency on chokinar.

Fixes #211.

### CODE REVIEW

**Comment by GeorchW** [comment]
Uhm, Travis is failing the tests on Linux only, without further output, and it works on my machine. What's going on there?

(Same issue with my other PR, #253 .)

**Comment by stefanforsberg** [comment]
Hey  @GeorchW. Would you mind merging the latest from master to this PR and I will take a look at it.

**Comment by GeorchW** [comment]
Sure.

**Comment by GeorchW** [comment]
Oops, I've realized that this PR breaks the Watch functionality. I didn't realize that it existed, since I've just glanced over the README and over-looked the fact that it's only activatable through a setting. Could fix this, though.

Notes to myself on how to fix it:

- [ ] Move code to delete the results file out of the parsing logic
- [ ] Only delete results files after the responsible process terminated, including the watch process, to avoid exceptions being thrown by accessing non-released file handles
- [ ] Activate file watching again, but only for `dotnet watch`

**Comment by GeorchW** [comment]
Alternatively, since we're already parsing the `dotnet watch test` output, we can just additionally look for the string `Results File: ...`, and then start parsing that file. I think I'll do that.

**Comment by GeorchW** [comment]
Okay, I've done the latter now; I think it's a much cleaner solution. See also the comments on the respective [commit](https://github.com/formulahendry/vscode-dotnet-test-explorer/pull/252/commits/410a1edcd3067dac2c43eabdb173f9d74d787c4a)

File: src/watch.ts [hunk 1]
```diff
@@ -41,20 +41,46 @@ export class Watch {
...
+            const lines = [];
+            const lineSegments = stdout.split("\n");
+            for (let i = 0; i < lineSegments.length; i++) {
+                const lineSegment = lineSegments[i];
+                const hadNewline = i > 0;
+                startedLine.push(lineSegment);
+                if (hadNewline) {
+                    const line = startedLine.join("");
+                    startedLine = [];
+                    lines.push(line);
```
Comment (stefanforsberg) [inline src/watch.ts:69]: When I test ran on my machine the lines seems to contain some whitespace which causes the equals check on line 77 to never become true. I guess this might be different on different OS (I'm on windows) but if I add a trim here bofre adding line to lines array it works better. Thoughts from you on this?

Comment (GeorchW) [reply src/watch.ts:69]: Hmm, I know that the `dotnet watch` command feeds the strings `"watch : "`, `"Started.\n"` into stdout on my machine. If we were to trim them, we would get something like `"watch :Started"`, which would not match further down.

Could you give me some samples on which strings are being fed into `buf` here on your machine?

Comment (GeorchW) [reply src/watch.ts:69]: Oh, sorry, I just realized you meant the classical CRLF line ending issue - line endings are `'\n'` on linux, `'\r'` on Mac and `"\r\n"` on Windows. We should split on both, to avoid running into the same issue on Mac. I'll write some code and push it.

Comment (GeorchW) [reply src/watch.ts:68]: Done.
